/**
 * 
 */
package com.eharmony.matching.vw.webservice.core;

import com.eharmony.matching.vw.webservice.core.vwexample.Example;
import com.eharmony.matching.vw.webservice.core.vwprediction.Prediction;

/**
 * @author vrahimtoola Submits examples to VW and returns predictions from it.
 */
public interface VWPredictor {

	// TODO: look at guava's Function interface
	// change String generic type to something more type safe.

	/*
	 * Submits the examples to be evaluated, to VW.
	 * 
	 * @param examples An iterable containing the VW examples. Must not be null
	 * (but can be empty).
	 * 
	 * @returns The predictions, as generated by VW. May be empty, but never
	 * null. The strings in this iterable will be exactly as they've been
	 * returned by VW, no extra processing/massaging will be done.
	 */
	Iterable<Prediction> predict(Iterable<Example> examples)
			throws ExampleSubmissionException, PredictionFetchException;
}
